@host = http://localhost:5209
@cardId = <uuid>

### Создать карточку
POST {{host}}/api/cards
Content-Type: application/json

{
  "recipientName": "User",
  "birthDate": "1990-05-04"
}

### Получить карточку по Id
GET {{host}}/api/cards/{{cardId}}

## Получить все карточки
GET {{host}}/api/cards
