// <auto-generated />
using System;
using HappyDeathdayApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HappyDeathdayApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260517235253_AddLifeExpectancy")]
    partial class AddLifeExpectancy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HappyDeathdayApi.Models.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Lang")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("HappyDeathdayApi.Models.LifeExpectancySetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("UpdatedAt")
                        .HasColumnType("date");

                    b.Property<double>("Years")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode", "Gender")
                        .IsUnique();

                    b.ToTable("LifeExpectancySettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryCode = "WW",
                            Gender = "Male",
                            UpdatedAt = new DateOnly(2023, 1, 1),
                            Years = 70.549999999999997
                        },
                        new
                        {
                            Id = 2,
                            CountryCode = "WW",
                            Gender = "Female",
                            UpdatedAt = new DateOnly(2023, 1, 1),
                            Years = 75.890000000000001
                        },
                        new
                        {
                            Id = 3,
                            CountryCode = "RU",
                            Gender = "Male",
                            UpdatedAt = new DateOnly(2023, 1, 1),
                            Years = 67.260000000000005
                        },
                        new
                        {
                            Id = 4,
                            CountryCode = "RU",
                            Gender = "Female",
                            UpdatedAt = new DateOnly(2023, 1, 1),
                            Years = 79.040000000000006
                        },
                        new
                        {
                            Id = 5,
                            CountryCode = "UA",
                            Gender = "Male",
                            UpdatedAt = new DateOnly(2023, 1, 1),
                            Years = 66.900000000000006
                        },
                        new
                        {
                            Id = 6,
                            CountryCode = "UA",
                            Gender = "Female",
                            UpdatedAt = new DateOnly(2023, 1, 1),
                            Years = 80.200000000000003
                        },
                        new
                        {
                            Id = 7,
                            CountryCode = "BY",
                            Gender = "Male",
                            UpdatedAt = new DateOnly(2023, 1, 1),
                            Years = 69.530000000000001
                        },
                        new
                        {
                            Id = 8,
                            CountryCode = "BY",
                            Gender = "Female",
                            UpdatedAt = new DateOnly(2023, 1, 1),
                            Years = 79.060000000000002
                        },
                        new
                        {
                            Id = 9,
                            CountryCode = "KZ",
                            Gender = "Male",
                            UpdatedAt = new DateOnly(2023, 1, 1),
                            Years = 70.109999999999999
                        },
                        new
                        {
                            Id = 10,
                            CountryCode = "KZ",
                            Gender = "Female",
                            UpdatedAt = new DateOnly(2023, 1, 1),
                            Years = 78.390000000000001
                        },
                        new
                        {
                            Id = 11,
                            CountryCode = "UZ",
                            Gender = "Male",
                            UpdatedAt = new DateOnly(2023, 1, 1),
                            Years = 69.450000000000003
                        },
                        new
                        {
                            Id = 12,
                            CountryCode = "UZ",
                            Gender = "Female",
                            UpdatedAt = new DateOnly(2023, 1, 1),
                            Years = 75.400000000000006
                        },
                        new
                        {
                            Id = 13,
                            CountryCode = "GE",
                            Gender = "Male",
                            UpdatedAt = new DateOnly(2023, 1, 1),
                            Years = 69.569999999999993
                        },
                        new
                        {
                            Id = 14,
                            CountryCode = "GE",
                            Gender = "Female",
                            UpdatedAt = new DateOnly(2023, 1, 1),
                            Years = 79.109999999999999
                        },
                        new
                        {
                            Id = 15,
                            CountryCode = "AM",
                            Gender = "Male",
                            UpdatedAt = new DateOnly(2023, 1, 1),
                            Years = 71.390000000000001
                        },
                        new
                        {
                            Id = 16,
                            CountryCode = "AM",
                            Gender = "Female",
                            UpdatedAt = new DateOnly(2023, 1, 1),
                            Years = 79.450000000000003
                        },
                        new
                        {
                            Id = 17,
                            CountryCode = "IL",
                            Gender = "Male",
                            UpdatedAt = new DateOnly(2023, 1, 1),
                            Years = 80.180000000000007
                        },
                        new
                        {
                            Id = 18,
                            CountryCode = "IL",
                            Gender = "Female",
                            UpdatedAt = new DateOnly(2023, 1, 1),
                            Years = 84.590000000000003
                        },
                        new
                        {
                            Id = 19,
                            CountryCode = "US",
                            Gender = "Male",
                            UpdatedAt = new DateOnly(2023, 1, 1),
                            Years = 76.859999999999999
                        },
                        new
                        {
                            Id = 20,
                            CountryCode = "US",
                            Gender = "Female",
                            UpdatedAt = new DateOnly(2023, 1, 1),
                            Years = 81.849999999999994
                        },
                        new
                        {
                            Id = 21,
                            CountryCode = "GB",
                            Gender = "Male",
                            UpdatedAt = new DateOnly(2023, 1, 1),
                            Years = 79.359999999999999
                        },
                        new
                        {
                            Id = 22,
                            CountryCode = "GB",
                            Gender = "Female",
                            UpdatedAt = new DateOnly(2023, 1, 1),
                            Years = 83.209999999999994
                        },
                        new
                        {
                            Id = 23,
                            CountryCode = "CA",
                            Gender = "Male",
                            UpdatedAt = new DateOnly(2023, 1, 1),
                            Years = 80.430000000000007
                        },
                        new
                        {
                            Id = 24,
                            CountryCode = "CA",
                            Gender = "Female",
                            UpdatedAt = new DateOnly(2023, 1, 1),
                            Years = 84.829999999999998
                        },
                        new
                        {
                            Id = 25,
                            CountryCode = "AU",
                            Gender = "Male",
                            UpdatedAt = new DateOnly(2023, 1, 1),
                            Years = 82.099999999999994
                        },
                        new
                        {
                            Id = 26,
                            CountryCode = "AU",
                            Gender = "Female",
                            UpdatedAt = new DateOnly(2023, 1, 1),
                            Years = 85.739999999999995
                        },
                        new
                        {
                            Id = 27,
                            CountryCode = "DE",
                            Gender = "Male",
                            UpdatedAt = new DateOnly(2023, 1, 1),
                            Years = 79.019999999999996
                        },
                        new
                        {
                            Id = 28,
                            CountryCode = "DE",
                            Gender = "Female",
                            UpdatedAt = new DateOnly(2023, 1, 1),
                            Years = 83.760000000000005
                        },
                        new
                        {
                            Id = 29,
                            CountryCode = "FR",
                            Gender = "Male",
                            UpdatedAt = new DateOnly(2023, 1, 1),
                            Years = 80.430000000000007
                        },
                        new
                        {
                            Id = 30,
                            CountryCode = "FR",
                            Gender = "Female",
                            UpdatedAt = new DateOnly(2023, 1, 1),
                            Years = 86.090000000000003
                        },
                        new
                        {
                            Id = 31,
                            CountryCode = "PL",
                            Gender = "Male",
                            UpdatedAt = new DateOnly(2023, 1, 1),
                            Years = 74.879999999999995
                        },
                        new
                        {
                            Id = 32,
                            CountryCode = "PL",
                            Gender = "Female",
                            UpdatedAt = new DateOnly(2023, 1, 1),
                            Years = 82.349999999999994
                        },
                        new
                        {
                            Id = 33,
                            CountryCode = "ES",
                            Gender = "Male",
                            UpdatedAt = new DateOnly(2023, 1, 1),
                            Years = 80.959999999999994
                        },
                        new
                        {
                            Id = 34,
                            CountryCode = "ES",
                            Gender = "Female",
                            UpdatedAt = new DateOnly(2023, 1, 1),
                            Years = 86.310000000000002
                        },
                        new
                        {
                            Id = 35,
                            CountryCode = "IT",
                            Gender = "Male",
                            UpdatedAt = new DateOnly(2023, 1, 1),
                            Years = 81.569999999999993
                        },
                        new
                        {
                            Id = 36,
                            CountryCode = "IT",
                            Gender = "Female",
                            UpdatedAt = new DateOnly(2023, 1, 1),
                            Years = 85.75
                        },
                        new
                        {
                            Id = 37,
                            CountryCode = "NL",
                            Gender = "Male",
                            UpdatedAt = new DateOnly(2023, 1, 1),
                            Years = 80.540000000000006
                        },
                        new
                        {
                            Id = 38,
                            CountryCode = "NL",
                            Gender = "Female",
                            UpdatedAt = new DateOnly(2023, 1, 1),
                            Years = 83.739999999999995
                        },
                        new
                        {
                            Id = 39,
                            CountryCode = "RS",
                            Gender = "Male",
                            UpdatedAt = new DateOnly(2023, 1, 1),
                            Years = 73.5
                        },
                        new
                        {
                            Id = 40,
                            CountryCode = "RS",
                            Gender = "Female",
                            UpdatedAt = new DateOnly(2023, 1, 1),
                            Years = 80.040000000000006
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
